language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run client.lint
  - npm run common.lint
  - npm run server.lint
  - npm run test
  - npm run server.prod
  - npm run browser.prod
deploy:
  provider: heroku
  api_key:
    secure: 5CsxK36dOCuEO9JM/H6M68415gLVrFjsFZPMT4k9DahbCakXNfNYk3259PTyuH66y3M11PeA5TGbY2RGAGDHZaHIHn5Htjhpi0w+iMLliTcBih2kymmBWXdTfw9KFsiZ/Uic7MTUdGwn1sYxslxWzStqnk+IlhTEPQM4DN+a8cZEScU5DPbf8uVdEWb5AiTsF2hQZpvPFp754YRPLKPTWvKK02Iu5i6HIg6Y8Pj/h+TMpXFmzENQ/Zd8iGtpBc4TBpKFiQ5Q28xCDGcM78Cd/LkNgUBa6uqghCSuRvsPfRdbzt/+7s4tycY8t6gLRVijFJakOn125A2qWip2ICnCwn5Dc0qXIcaaWnrx6kwPd9CO3ZCL9UQiFkIUEKh+YaZYjIqUvw8Fw2ieeq6txf0vC4L3nhRIazVUqjNcoTaDAL28gk9S4lpq2khjBgHJxnc6/RIBOTrEgGnKHuBc5tm1sEZ9ZDFKr0JtdBW4+scjQFynrQ+DDwPK2mtaqvgE8hjM/ivrFpj21Wuyq1sn0ryrqxS0p4xxuSpb/GX9xgoCWOplFQMsmIsgT+0LEP2FHfAA4I/G/w3Qx0Osp3ncqc+0N/wcdFXd0AQBKNUJO4ulox9vsTIrqA1+B52kZps/5kXODpVwDmEfjDuxQ13pquv9X1fdTiFQWjL9hlmsRAm8K7Y=
  app:
    develop: discipuli-staging
